version: '3'
services:
  app : 
    container_name: docker-node-docker-node-mongodb
    restart: always
    build: .
    ports: 
      - 80:3000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017